[project]
name = "ai-agents"
version = "0.1.0"
description = "My first AI agent"
readme = "README.md"
requires-python = ">=3.12.6"
dependencies = [
    "firecrawl-py>=2.16.3",
    "openai>=1.98.0",
    ]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
